services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    container_name: mysql
    ports:
      - "3333:3306"
    env_file:
      - ./src/main/resources/.env
#    volumes:
#      - mysql_data:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  mysql_data:
